### ISSUE TITLE
README: GET points to create action

### ISSUE THREAD

**Issue by ACPK** [slogsdon/placid#15]
In the readme V1 example, why does GET point to create?

```
get  "/pages",          Handlers.V1.Pages, :create
```

**Comment by slogsdon** [comment]
Hey @ACPK! Great question. When I first wrote this section, I was wanting to show progress between `v1` and `v2` in how the hypothetical project was implemented. This was mainly to show differences in the two versions and is in no way a requirement for you to use.

If that wasn't clear, let me know, and I can always add a bit of explanatory text in that portion of the readme.

**Comment by ACPK** [comment]
@slogsdon I was more thinking that a create action should be a POST.

**Comment by slogsdon** [comment]
@ACPK I completely understand and agree with you, and there is a `POST` with the `:create` action in the first version of that readme example. Here's the message I'm trying to convey.

Version "1" starts with a not so good API, and it contains some not so useful and/or confusing endpoints like the two you pointed out:

```elixir
  version "1" do
    # ...
    get  "/pages",          Handlers.V1.Pages, :create
    post "/pages",          Handlers.V1.Pages, :create
    # ...
  end
```

The developer then sees that the API can be improved, and one of the bits she changes is the `get "/pages"` route:

```elixir
  version "2" do
    # ...
    post "/pages",          Handlers.V2.Pages, :create 
    # ...
  end
```

This hypothetical developer noticed what you noticed, that the route she removed did not make any sense for the API at hand.

Again, this is just supposed to be a contrived example to show some progression between the API versions. I wouldn't look too much into it :smile:
