### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by jtmoulia** [slogsdon/placid#7]
Hey, any thought on websocket support in placid?

Looks like you're using cowboy under the hood which supports websockets, and I'd think you could make it work with the existing style:

```elixir
websocket "/ws", Handlers.V2.WebSocket
```
The `Handlers.V2.WebSocket` could implement some placid websocket behavior.

I wouldn't mind taking this on if you think it fits in!

**Comment by slogsdon** [comment]
@jtmoulia I know this was almost a year ago, but I'm going to make an executive decision based on recent work.

I'm going to leave WebSocket stuff out of Placid for the time being. Projects like https://github.com/slogsdon/plug-web-socket should be able to provide the core WebSocket functionality which can be easily integrated with Placid. While the necessary handler code requires a bit of boilerplate (see below), this can always be countered with some extra macros the integrating developer could create.

```elixir
defmodule MyApp.TopicController do
  def handle(:init, state) do
    {:ok, state}
  end
  def handle(:terminate, _state) do
    :ok
  end
  def handle("topic:" <> letter, state, data) do
    payload = %{awesome: "blah #{letter}",
                orig: data}
    {:reply, {:text, payload}, state}
  end
end
```

Feel free to open this back up if you still feel strongly about it, and thanks for the initial push!

**Comment by jtmoulia** [comment]
Sounds like a well-thought out approach -- thanks for pushing Elixir support for websockets along ;)
